"""add sentiment_score to reddit_comments

Revision ID: 186496ec9189
Revises: 3805b3192baa
Create Date: 2026-04-25 14:58:29.175435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '186496ec9189'
down_revision: Union[str, None] = '3805b3192baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reddit_comments', sa.Column('sentiment_score', sa.Float(), nullable=True))
    op.drop_index(op.f('idx_sub_themes_centroid'), table_name='sub_themes', postgresql_ops={'centroid': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.alter_column('system_settings', 'value',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_settings', 'value',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False)
    op.create_index(op.f('idx_sub_themes_centroid'), 'sub_themes', ['centroid'], unique=False, postgresql_ops={'centroid': 'vector_cosine_ops'}, postgresql_with={'lists': '10'}, postgresql_using='ivfflat')
    op.drop_column('reddit_comments', 'sentiment_score')
    # ### end Alembic commands ###
