from .ingestion import INGESTION_BEAT_SCHEDULE
from .discovery import DISCOVERY_BEAT_SCHEDULE
from .notifications import NOTIFICATIONS_BEAT_SCHEDULE

BEAT_SCHEDULE = {
    **INGESTION_BEAT_SCHEDULE,
    **DISCOVERY_BEAT_SCHEDULE,
    **NOTIFICATIONS_BEAT_SCHEDULE,
}
