-- =============================================================
-- Low-Level Design: Database Schema
-- PostgreSQL 15+ with pgvector extension
-- =============================================================
-- Raw articles (pre-deduplication) are stored in MongoDB, not PostgreSQL.
-- PostgreSQL only stores articles that have passed stage 1 (deduplication).
-- Alert threshold checks compare user's topic threshold against
-- relevance_score only. credibility_score is stored for transparency
-- but does not affect alerting logic.

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;

-- -------------------------------------------------------------
-- 1. USERS
-- -------------------------------------------------------------
CREATE TABLE users (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name             TEXT NOT NULL,
    email            TEXT NOT NULL UNIQUE,
    password_hash    TEXT NOT NULL,
    phone_number     TEXT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_users_email ON users (email);

CREATE TABLE refresh_tokens (
    id          UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id     UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token_hash  TEXT NOT NULL UNIQUE,
    expires_at  TIMESTAMPTZ NOT NULL,
    is_revoked  BOOLEAN NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_refresh_tokens_user_id ON refresh_tokens(user_id);

-- -------------------------------------------------------------
-- 2. SOURCES
-- Curated list of RSS feeds, Reddit, Hacker News.
-- Managed by admins — not user-configurable in v1.
-- -------------------------------------------------------------
CREATE TABLE sources (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name             TEXT NOT NULL,
    url              TEXT NOT NULL UNIQUE,
    type             TEXT NOT NULL,
    credibility_score FLOAT NOT NULL DEFAULT 0.5 CHECK (credibility_score BETWEEN 0 AND 1),
    poll_interval    INT NOT NULL DEFAULT 600,   -- seconds; default 10 mins
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    last_crawled_at  TIMESTAMPTZ
);

-- -------------------------------------------------------------
-- 3. TOPICS
-- Each topic belongs to one user.
-- description: optional user-provided keywords or context.
-- expanded_description: Gemini-generated expansion of name +
-- description. This is what Sentence-BERT embeds, not the raw
-- name.
-- embedding: generated from expanded_description via
-- Sentence-BERT.
-- threshold: min relevance score to trigger an alert (0.0â€“1.0).
-- -------------------------------------------------------------
CREATE TABLE topics (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id          UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    name             TEXT NOT NULL,
    description      TEXT,
    expanded_description TEXT,
    embedding        VECTOR(384),               -- generated by Sentence-BERT
    threshold        FLOAT NOT NULL DEFAULT 0.7 CHECK (threshold BETWEEN 0 AND 1),
    is_active        BOOLEAN NOT NULL DEFAULT TRUE,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER topics_updated_at
    BEFORE UPDATE ON topics
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at();

CREATE INDEX idx_topics_user_id ON topics (user_id);

-- -------------------------------------------------------------
-- 4. TOPIC CHANNELS
-- One topic can have multiple delivery channels.
-- Separated from topics table to support multi-channel per topic.
-- -------------------------------------------------------------
CREATE TABLE topic_channels (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    topic_id         UUID NOT NULL REFERENCES topics (id) ON DELETE CASCADE,
    channel          TEXT NOT NULL CHECK (channel IN ('email', 'sms', 'websocket')),
    UNIQUE (topic_id, channel)                  -- one row per channel per topic
);

CREATE INDEX idx_topic_channels_topic_id ON topic_channels (topic_id);

-- -------------------------------------------------------------
-- 5. ARTICLES
-- Rejected articles are not stored in PostgreSQL - they are
-- discarded at the pipeline stage. Only articles that pass
-- deduplication are written here.
--
-- pipeline_status values:
--   passed_dedup         -> survived stage 1 (deduplication)
--   processed            -> survived all stages, summary generated
--
-- embedding: Sentence-BERT vector for deduplication.
-- summary: generated once by Gemini, reused for all matching users.
-- -------------------------------------------------------------
CREATE TABLE articles (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source_id        UUID NOT NULL REFERENCES sources (id),
    url              TEXT NOT NULL UNIQUE,
    headline         TEXT NOT NULL,
    content          TEXT,
    summary          TEXT,                      -- NULL until stage 5 completes
    embedding        VECTOR(384),
    pipeline_status  TEXT NOT NULL DEFAULT 'passed_dedup'
                         CHECK (pipeline_status IN ('passed_dedup', 'processed')),
    published_at     TIMESTAMPTZ,
    crawled_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_articles_url        ON articles (url);
CREATE INDEX idx_articles_source_id  ON articles (source_id);
CREATE INDEX idx_articles_crawled_at ON articles (crawled_at DESC);

-- pgvector IVFFlat index for fast ANN search during dedup + novelty detection
CREATE INDEX idx_articles_embedding ON articles
    USING ivfflat (embedding vector_cosine_ops) WITH (lists = 100);

-- -------------------------------------------------------------
-- 6. ARTICLE TOPIC MATCHES
-- Junction table: many-to-many between articles and topics.
-- relevance_score : raw cosine similarity (Sentence-BERT)
-- credibility_score: copied from sources.credibility_score at match time
-- Alert threshold checks compare topic.threshold against relevance_score.
-- -------------------------------------------------------------
CREATE TABLE article_topic_matches (
    id                UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    article_id        UUID NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
    topic_id          UUID NOT NULL REFERENCES topics (id) ON DELETE CASCADE,
    relevance_score   FLOAT NOT NULL CHECK (relevance_score BETWEEN 0 AND 1),
    credibility_score FLOAT NOT NULL CHECK (credibility_score BETWEEN 0 AND 1),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (article_id, topic_id)               -- one match row per pair
);

CREATE INDEX idx_atm_article_id ON article_topic_matches (article_id);
CREATE INDEX idx_atm_topic_id   ON article_topic_matches (topic_id);

-- relevance_score is also denormalized from article_topic_matches for the
-- same reason.
-- -------------------------------------------------------------
-- 7. ALERTS
-- Delivery history. One row per user per article per channel.
-- topic_id is denormalized here (also derivable via article_topic_matches)
-- to avoid joins on every dashboard read — intentional denormalization.
-- -------------------------------------------------------------
CREATE TABLE alerts (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id          UUID NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    article_id       UUID NOT NULL REFERENCES articles (id),
    topic_id         UUID NOT NULL REFERENCES topics (id),
    relevance_score  FLOAT NOT NULL CHECK (relevance_score BETWEEN 0 AND 1),
    channel          TEXT NOT NULL CHECK (channel IN ('email', 'sms', 'websocket')),
    status           TEXT NOT NULL DEFAULT 'pending'
                         CHECK (status IN ('pending', 'sent', 'failed')),
    sent_at          TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_alerts_user_id    ON alerts (user_id);
CREATE INDEX idx_alerts_status     ON alerts (status);
CREATE INDEX idx_alerts_created_at ON alerts (created_at DESC);

-- -------------------------------------------------------------
-- 8. TREND SNAPSHOTS
-- Written by the analytics Kafka consumer (independent of
-- the processing pipeline consumer).
-- Tracks article volume per topic per hour to detect unusual
-- activity spikes compared to 7-day rolling baseline.
-- Powers the GET /analytics/trends endpoint.
-- -------------------------------------------------------------
CREATE TABLE trend_snapshots (
    id               UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    topic_id         UUID NOT NULL REFERENCES topics (id)
                         ON DELETE CASCADE,
    snapshot_hour    TIMESTAMPTZ NOT NULL,
    article_count    INT NOT NULL DEFAULT 0,
    avg_relevance    FLOAT,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (topic_id, snapshot_hour)
);

CREATE INDEX idx_trend_snapshots_topic_id
    ON trend_snapshots (topic_id);
CREATE INDEX idx_trend_snapshots_hour
    ON trend_snapshots (snapshot_hour DESC);
